name: {{project_name.snakeCase()}}

packages:
  - core/*/*
  - features/*/*
  - .

scripts:
  clean:
    description: Clean all packages.
    exec: flutter clean
    select-package:
      flutter: true

  pub_get:
    description: Get dependencies in all packages.
    exec: flutter pub get
    select-package:
      flutter: true

  upgrade:
    description: Upgrade dependencies (point to last commit).
    exec: flutter packages upgrade
    select-package:
      flutter: true

  analyze:
    description: Analyze all packages.
    exec: flutter analyze .
    select-package:
      flutter: true

  test:
    description: Run tests in all packages.
    run: flutter test --coverage
    exec:
      concurrency: 1
      failFast: true
      noSelect: true
    select-package:
      flutter: true
      dir-exists:
        - test
